# Generated by Django 4.1.4 on 2023-01-11 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('src', models.CharField(max_length=500)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AudioPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='AudioPlaylistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('audio_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stream.audioitem')),
                ('audio_playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stream.audioplaylist')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='VideoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('src', models.CharField(max_length=500)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='VideoPlaylistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('video_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stream.videoitem')),
                ('video_playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stream.videoplaylist')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.DeleteModel(
            name='ListenItem',
        ),
        migrations.DeleteModel(
            name='WatchItem',
        ),
        migrations.AddField(
            model_name='videoplaylist',
            name='items',
            field=models.ManyToManyField(through='stream.VideoPlaylistItem', to='stream.videoitem'),
        ),
        migrations.AddField(
            model_name='audioplaylist',
            name='items',
            field=models.ManyToManyField(through='stream.AudioPlaylistItem', to='stream.audioitem'),
        ),
    ]
