# Generated by Django 4.1.4 on 2023-01-31 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='thumbnail_src',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
