# Generated by Django 4.1.4 on 2023-01-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0002_audioitem_audioplaylist_audioplaylistitem_videoitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audioplaylist',
            name='date',
        ),
        migrations.RemoveField(
            model_name='videoplaylist',
            name='date',
        ),
        migrations.AddField(
            model_name='audioplaylist',
            name='day_of_week',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videoplaylist',
            name='day_of_week',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
