# Generated by Django 4.1.4 on 2022-12-29 22:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('listen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listenitem',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
